<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sample_call</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="dongjae@example.com">hkit</maintainer>
  <license>TODO: License declaration</license>

  <!-- Python ROS 2 노드 실행에 필요한 라이브러리 -->
  <depend>rclpy</depend>

  <!-- AskLLM 서비스 인터페이스를 제공하는 패키지 -->
  <depend>llm_ros2</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
